# Generated by Django 4.2.3 on 2026-09-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'دراجة نارية / سكوتر'), ('CAR', 'سيارة'), ('BICYCLE', 'دراجة هوائية')], default='MOTORCYCLE', max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=50)),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل ومستعد للعمل')),
                ('is_busy', models.BooleanField(default=False, verbose_name='في مهمة توصيل حالية')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_delivered_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=5.0)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0.0, help_text='المديونية الكاش المتراكمة', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFFERED', 'تم إرسال العرض للكابتن'), ('ACCEPTED', 'الكابتن قبل الطلب ومتجه للمطعم'), ('ARRIVED_AT_STORE', 'وصل إلى المطعم'), ('PICKED_UP', 'استلم الطلب وفي الطريق للعميل'), ('ARRIVED_AT_CUSTOMER', 'وصل إلى موقع العميل'), ('COMPLETED', 'تم التسليم بنجاح'), ('CANCELLED', 'تم إلغاء مهمة التوصيل')], default='OFFERED', max_length=30)),
                ('delivery_otp', models.CharField(editable=False, help_text='كود التحقق لإثبات التسليم', max_length=6)),
                ('distance_km', models.FloatField(default=0.0)),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_trips', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_trip', to='orders.order')),
            ],
        ),
    ]
