# Generated by Django 5.1.15 on 2026-09-17 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytrip',
            name='dispatch_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد محاولات التعيين'),
        ),
        migrations.AddField(
            model_name='deliverytrip',
            name='last_offered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_trips', to=settings.AUTH_USER_MODEL, verbose_name='آخر كابتن عُرض عليه الطلب'),
        ),
        migrations.AlterField(
            model_name='deliverytrip',
            name='status',
            field=models.CharField(choices=[('DISPATCHING', 'جاري البحث عن كابتن آلياً'), ('OFFERED', 'تم إرسال العرض للكابتن'), ('ACCEPTED', 'الكابتن قبل الطلب ومتجه للمطعم'), ('ARRIVED_AT_STORE', 'وصل إلى المطعم'), ('PICKED_UP', 'استلم الطلب وفي الطريق للعميل'), ('ARRIVED_AT_CUSTOMER', 'وصل إلى موقع العميل'), ('COMPLETED', 'تم التسليم بنجاح'), ('MANUAL_DISPATCH_REQUIRED', 'مطلوب تعيين يدوي (فشل آلي)'), ('CANCELLED', 'تم إلغاء مهمة التوصيل')], default='DISPATCHING', max_length=30),
        ),
    ]
