# Generated by Django 5.1.15 on 2026-10-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_deliverytrip_dispatch_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDriver',
            fields=[
            ],
            options={
                'verbose_name': 'طلب انضمام كابتن جديد',
                'verbose_name_plural': 'طلبات انضمام الكباتن الجدد ⏳',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('deliveries.driverprofile',),
        ),
    ]
