# Generated by Django 5.1.15 on 2026-10-07 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_pendingdriver'),
        ('orders', '0002_order_delivery_distance_km_order_delivery_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.PositiveIntegerField(default=1, verbose_name='رقم الدفعة')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار استجابة الكابتن ⏳'), ('ACCEPTED', 'تم القبول من الكابتن ✅'), ('REJECTED', 'تم الرفض يدوياً ❌'), ('TIMED_OUT', 'انتهت مهلة الرد ⏱️'), ('EXPIRED', 'سبقه كابتن آخر 💨'), ('REVOKED', 'ملغي / مسحوب 🚫')], default='PENDING', max_length=20, verbose_name='حالة العرض')),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='أرباح الكابتن المقدرة')),
                ('estimated_distance_km', models.FloatField(default=0.0, verbose_name='المسافة للمطعم (كم)')),
                ('is_manual', models.BooleanField(default=False, verbose_name='مرسل يدوياً من الإدارة')),
                ('offered_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت إرسال العرض')),
                ('expires_at', models.DateTimeField(verbose_name='وقت انتهاء الصلاحية')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستجابة')),
                ('response_time_seconds', models.FloatField(blank=True, null=True, verbose_name='سرعة الاستجابة (ثواني)')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL, verbose_name='الكابتن')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_offers', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عرض توصيل لكابتن',
                'verbose_name_plural': 'عروض التوصيل للكباتن 🎯',
                'ordering': ['-offered_at'],
            },
        ),
    ]
