# Generated by Django 4.2.3 on 2026-09-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المطعم')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='وصف المطعم')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('address_text', models.CharField(max_length=255, verbose_name='العنوان النصي')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_radius_km', models.FloatField(default=10.0, verbose_name='نصف قطر التوصيل بالكيلومتر')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='عملة المطعم (ديناميكية حسب المنطقة)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='رسوم التوصيل الأساسية')),
                ('estimated_prep_time_minutes', models.PositiveIntegerField(default=25, verbose_name='متوسط وقت التحضير بالدقائق')),
                ('rating', models.FloatField(default=5.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح ومفعل')),
                ('is_busy', models.BooleanField(default=False, verbose_name='وضع الذروة / المشغول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم النطاق')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('polygon_coordinates', models.JSONField(default=list, help_text='مضلع النطاق الجغرافي GeoJSON Polygon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'day')},
            },
        ),
    ]
