# Generated by Django 5.1.15 on 2026-09-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['city', 'name'], 'verbose_name': 'منطقة توصيل', 'verbose_name_plural': 'مناطق التوصيل'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'مطعم', 'verbose_name_plural': 'المطاعم'},
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='رسوم التوصيل الأساسية للمنطقة'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='city',
            field=models.CharField(default='الرياض', max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='currency',
            field=models.CharField(default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعلة للتوصيل'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_zones',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.deliveryzone', verbose_name='مناطق التوصيل المغطاة'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المنطقة / النطاق'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='إحداثيات المضلع الجغرافي GeoJSON Polygon [[lat, lng], ...]'),
        ),
    ]
