# Generated by Django 5.1.15 on 2026-09-17 22:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_deliveryzone_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='انقر على الخريطة لرسم حدود المنطقة، وانقر مرتين لإغلاق المضلع.', null=True, srid=4326, verbose_name='مضلع النطاق على الخريطة'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='يتم توليدها وتحديثها تلقائياً من الخريطة بصيغة [[lat, lng], ...]', verbose_name='إحداثيات المضلع (GeoJSON)'),
        ),
    ]
