# Generated by Django 5.1.15 on 2026-09-17 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_currency'),
        ('restaurants', '0003_deliveryzone_polygon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='currency',
            field=models.ForeignKey(default='SAR', help_text='اختر العملة المعتمدة لهذه المنطقة من قائمة عملات المنصة', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_zones', to='payments.currency', verbose_name='العملة المعتمدة للمنطقة'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='currency',
            field=models.ForeignKey(default='SAR', help_text='العملة المعتمدة لأسعار المطعم', on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='payments.currency', verbose_name='عملة المطعم'),
        ),
    ]
