# Generated by Django 5.1.15 on 2026-09-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_deliveryzone_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='auto_surge_percent',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='نسبة زيادة الذروة التلقائية %'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='auto_surge_threshold_ratio',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='تتفعل الذروة إذا كان عدد الطلبات الجارية >= ضعف عدد الكباتن المتاحين', max_digits=4, verbose_name='معامل عتبة الذروة (الطلبات / الكباتن)'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='base_distance_km',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='المسافة المشمولة ضمن الرسوم الأساسية (مثلاً أول 3 كم)', max_digits=5, verbose_name='المسافة الأساسية المشمولة (كم)'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='is_auto_surge_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الذروة التلقائية حسب العرض والطلب'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='is_manual_surge_active',
            field=models.BooleanField(default=False, help_text='تفعيل فوري لرسوم إضافية للمنطقة بسبب الأمطار أو سوء الأحوال الجوية', verbose_name='تفعيل ذروة الطوارئ/الطقس يدوياً'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='manual_surge_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='نسبة زيادة ذروة الطقس %'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='max_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='سقف أقصى لرسوم التوصيل لمنع المبالغة في الأسعار', max_digits=10, verbose_name='الحد الأقصى لرسوم التوصيل'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='per_km_fee',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='الرسوم المضافة لكل كيلومتر بعد المسافة الأساسية', max_digits=5, verbose_name='سعر الكيلومتر الإضافي'),
        ),
    ]
