# Generated by Django 4.2.3 on 2026-09-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('delivery_address_snapshot', models.JSONField(default=dict, help_text='نسخة محفوظة من العنوان وقت الطلب')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار موافقة المطعم'), ('CONFIRMED', 'تم تأكيد الطلب'), ('PREPARING', 'قيد التحضير'), ('READY_FOR_PICKUP', 'جاهز للاستلام'), ('ON_THE_WAY', 'في الطريق مع الكابتن'), ('DELIVERED', 'تم التسليم بنجاح'), ('CANCELLED', 'تم الإلغاء')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('COD', 'الدفع عند الاستلام (كاش)'), ('CARD', 'بطاقة إلكترونية'), ('WALLET', 'المحفظة الإلكترونية')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'معلق'), ('PAID', 'مدفوع'), ('FAILED', 'فشل'), ('REFUNDED', 'مسترجع')], default='PENDING', max_length=20)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prep_time_minutes', models.PositiveIntegerField(default=25)),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات العميل للمطعم')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modifier_name', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.modifier')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
        ),
    ]
