# Generated by Django 5.1.15 on 2026-09-18 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0005_deliveryzone_auto_surge_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='مسافة التوصيل المقدرة بالكم'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.deliveryzone', verbose_name='منطقة التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_surge_applied',
            field=models.BooleanField(default=False, verbose_name='تم تطبيق رسوم ذروة'),
        ),
        migrations.AddField(
            model_name='order',
            name='surge_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الذروة المطبقة %'),
        ),
    ]
