# Generated by Django 5.1.15 on 2026-09-17 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0004_alter_deliveryzone_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='تقييم جودة الطعام (1-5)')),
                ('packaging_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='تقييم التغليف والنظافة (1-5)')),
                ('restaurant_comment', models.TextField(blank=True, verbose_name='تعليق على المطعم')),
                ('delivery_speed_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='سرعة التوصيل (1-5)')),
                ('driver_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='تقييم الكابتن وحسن التعامل (1-5)')),
                ('driver_comment', models.TextField(blank=True, verbose_name='تعليق على الكابتن')),
                ('merchant_reply', models.TextField(blank=True, verbose_name='رد صاحب المطعم')),
                ('merchant_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_reviews', to=settings.AUTH_USER_MODEL, verbose_name='الكابتن')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='الطلب')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant', verbose_name='المطعم')),
            ],
            options={
                'verbose_name': 'تقييم الطلب',
                'verbose_name_plural': 'تقييمات الطلبات والمراجعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
