# Generated by Django 5.1.15 on 2026-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='مثال: SAR, EGP, AED, KWD, USD', max_length=10, primary_key=True, serialize=False, verbose_name='رمز العملة (ISO)')),
                ('name', models.CharField(help_text='مثال: ريال سعودي، جنيه مصري', max_length=50, verbose_name='اسم العملة')),
                ('symbol', models.CharField(help_text='مثال: ر.س، ج.م، د.إ، $', max_length=10, verbose_name='علامة العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة للاستخدام في المنصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات المعتمدة',
                'ordering': ['code'],
            },
        ),
    ]
