# Generated by Django 5.1.15 on 2026-09-17 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_currency'),
        ('restaurants', '0004_alter_deliveryzone_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_code', models.CharField(max_length=50, unique=True, verbose_name='كود الدورة الأسبوعية')),
                ('start_date', models.DateField(verbose_name='بداية الفترة')),
                ('end_date', models.DateField(verbose_name='نهاية الفترة')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تم إغلاق الدورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دورة تسوية أسبوعية',
                'verbose_name_plural': 'دورات التسويات الأسبوعية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trips_count', models.PositiveIntegerField(default=0, verbose_name='عدد مشاوير التوصيل')),
                ('delivery_fees_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='أجور التوصيل المكتسبة')),
                ('cod_cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مبالغ الكاش المحصلة (COD)')),
                ('net_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد الصافي')),
                ('status', models.CharField(choices=[('PENDING', 'معلق'), ('SETTLED', 'تمت التسوية والتحويل'), ('DEBT_OWED', 'مطلوب توريد مديونية كاش')], default='PENDING', max_length=20, verbose_name='حالة التسوية')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='الكابتن')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_payouts', to='payments.payoutcycle', verbose_name='دورة التسوية')),
            ],
            options={
                'verbose_name': 'تسوية كابتن',
                'verbose_name_plural': 'تسويات الكباتن الأسبوعية',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات المسلمة')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي مبيعات الوجبات')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='نسبة عمولة المنصة %')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مبلغ عمولة المنصة')),
                ('net_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='صافي المستحق للمطعم')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد للتحويل'), ('PAID', 'تم التحويل بنجاح')], default='DRAFT', max_length=20, verbose_name='حالة التسوية')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='الرقم المرجعي للتحويل البنكي')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ وساعة التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payouts', to='payments.payoutcycle', verbose_name='دورة التسوية')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='restaurants.restaurant', verbose_name='المطعم')),
            ],
            options={
                'verbose_name': 'تسوية مطعم',
                'verbose_name_plural': 'تسويات المطاعم الأسبوعية',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'restaurant')},
            },
        ),
    ]
