# Generated by Django 5.1.15 on 2026-09-17 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم التذكرة')),
                ('user_role', models.CharField(max_length=20, verbose_name='صفة المستخدم')),
                ('category', models.CharField(choices=[('ORDER_ISSUE', 'مشكلة في الطلب'), ('DELIVERY_DELAY', 'تأخر التوصيل'), ('FOOD_QUALITY', 'جودة الطعام أو تلفه'), ('PAYMENT_DISPUTE', 'نزاع مالي أو استرداد'), ('DRIVER_ISSUE', 'مشكلة كابتن (عطل مركبة، إلخ)'), ('MERCHANT_INQUIRY', 'استفسار مطعم أو تسوية'), ('OTHER', 'أخرى')], default='ORDER_ISSUE', max_length=50, verbose_name='تصنيف الشكوى')),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'مرتفعة'), ('CRITICAL', 'حرجة / عاجلة')], default='MEDIUM', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة (جديدة)'), ('IN_PROGRESS', 'قيد المعالجة'), ('WAITING_USER', 'بانتظار رد المستخدم'), ('RESOLVED', 'تم الحل'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20, verbose_name='حالة التذكرة')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان التذكرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='موظف الدعم المسؤول')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.order', verbose_name='الطلب المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='صاحب التذكرة')),
            ],
            options={
                'verbose_name': 'تذكرة دعم فني',
                'verbose_name_plural': 'تذاكر الدعم الفني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField(verbose_name='نص الرسالة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/', verbose_name='مرفق')),
                ('is_internal_note', models.BooleanField(default=False, verbose_name='ملاحظة داخلية (لفريق الدعم فقط)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket', verbose_name='التذكرة')),
            ],
            options={
                'verbose_name': 'رسالة شات الدعم',
                'verbose_name_plural': 'رسائل شات الدعم',
                'ordering': ['created_at'],
            },
        ),
    ]
